---
title : "__`utilitR`__"
subtitle : "Une documentation utile pour R"
author : "Lino Galiana, Olivier Meslin"
institute : "Insee"
date : "`r Sys.Date()`"
output :
  xaringan::moon_reader :
    lib_dir : libs
    nature :
      highlightStyle : github
      highlightLines : true
      countIncrementalSlides : false
    self_contained : true
    chakra : 
      - ./libs/remark-latest.min.js
    css : 
    - css/default.css
    - css/default-fonts.css
    - custom.css
    - css/metropolis.css
    includes :
      after_body : insert-logo.html    
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


# Genèse du projet


Le projet `utilitR` est parti de deux constats : 

1. **Multiplicité d’obstacles dans la transition vers `R`** :
    + Diversité des environnements informatiques à l’Insee (poste local, AUS, plateforme innovation puis SSP-Cloud…) ;
    + Difficultés à s’approprier les outils et à en utiliser tout le potentiel :
    + Eclatement de la documentation de l'écosystème `R` ;
    + Multiplicité de *packages*, de qualité variable et parfois redondants ;
    + Barrière linguistique.
2. Il n'existe **pas de documentation de référence sur l'usage de `R` pour le statisticien** :
    +  La documentation de référence sur `SAS` en français, rédigée par
Axelle Chauvet et largement diffusée à l’Insee et dans le SSP, n'a pas d'équivalent en `R` ;
    + La documentation sur `R` est foisonnante mais propose peu d'exemples sur données réelles.

---
# Objectif du projet `utilitR`


Produire une documentation collaborative sur `R`, destinée principalement
aux agents du Service statistique public (mais pas seulement).

* La documentation vise à répondre à deux questions :
    1. Comment (bien) travailler avec `R` pour profiter de la richesse de son 
écosystème ;
    2. Comment réaliser des tâches élémentaires avec `R`.




---
# Contenu de la documentation `utilitR`

La documentation est structurée en deux parties :

* Travailler avec `R` à l'Insee :
    - Présentation des espaces de travail informatiques (AUSv3 et SSP Cloud) ;
    - Comment configurer sa session `R` ;
    - Comment installer et utiliser des _packages_ `R` ;
    - Comment utiliser RStudio et les `RProject` ;
    - Comment utiliser `git` et Gilab avec RStudio...

* Réaliser des tâches standard avec `R` : 
    - Importer des données (SAS, csv, txt, odt, xlsx...) ;
    - Manipuler des tables de données ;
    - Faire des graphiques ;
    - Manipuler des données textuelles ;
    - Manipuler des données spatiales ;
    - Rédiger des documents avec `R Markdown` ;
    - Utiliser des bases de données PostgreSQL et Oracle...


---
# Contenu de la documentation `utilitR`

Points d’originalité du projet :
+ **Approche (légèrement) normative** :
    - recommandations sur les _packages_ à utiliser ou à éviter, de façon à orienter
les agents vers les outils adaptés ;
    - conseils sur les bonnes pratiques à adopter ;
+ la plupart des exemples mobilisent des données disponibles sur [insee.fr](www.insee.fr) ;
+ **Les exemples sont reproductibles** :
    - la plupart des exemples mobilisent des données disponibles sur [insee.fr](www.insee.fr) ;

    
---
# Diffusion de la documentation `utilitR`

La documentation est diffusée sous deux formes :

- un site internet ([www.utilitr.org]) déjà disponible ;
- une brochure pdf imprimable (en cours d'élaboration).

-- 

Le site internet est actualisé en continu, tandis que la brochure pdf est publiée de façon ponctuelle et millésimée (version 1 attendue pour juin 2021).



    
---
# Diffusion de la documentation `utilitR`

La documentation est diffusée sous deux formes :

- un site internet ([www.utilitr.org]) déjà disponible ;
- une brochure pdf imprimable (en cours d'élaboration).

--

Le site internet est actualisé en continu, tandis que la brochure pdf est publiée de façon ponctuelle et millésimée (version 1 attendue pour juin 2021).

---









# Positionnement du projet `utilitR`

* Le projet est l’une des multiples initiatives lancées pour faciliter la
transition de l’Insee vers `R` : 
    + Supports du groupe de travail USSR ;
    + FunCamp dévéloppé par la Division Innovation et Instruction Technique (Diit) ;
    + Guide à l'usage du statisticien débutant (Cédric Afsa) ;
    + Formation Travail collaboratif avec `R` (en cours de développement).
* Les recommandations de *packages* sont cohérentes avec celles du COPS
* Prise en compte de l'évolution de l’environnement informatique du statisticien :
    + Tient compte de la modernisation des serveurs partagés (AUS) ;
    + Présentation de la plateforme [SSP-cloud](https ://datalab.sspcloud.fr/accueil) développée par la Diit ;
    + Présente des manières simples d'utiliser les outils assurant la qualité des projets en `R` comme le contrôle de version avec `Git`.


---

# Où en est le projet aujourd'hui ?

* Un portail d'accès sous forme de site *web* : <www.utilitr.org> :
    + La documentation principale est disponible sur <www.book.utilitr.org> ;
    + Guide des bonnes pratiques en `R` : <www.pratiques.utilitr.org>

S'il ne faut retenir qu'un lien [wwww.utilitr.org](wwww.utilitr.org)

* Tout est *open-source*, disponible sur [la page Github d'InseeFrLab](https ://github.com/InseeFrLab/utilitR)

* Prochaines étapes :
    + Version 1 : Juin 2021

---

# Comment est structurée la documentation ?

* Dans la documentation principale <www.book.utilitr.org> :
1. Comment réaliser des tâches élémentaires du statisticien avec `R` (fiches thématiques) ;
  * Import des données
  * Manipuler des données
  * Produire des représentations graphiques ou des rapports...
2. Comment configurer `R` pour tirer profit de l'écosystème disponible
  * 

* Dans le guide des bonnes pratiques <www.pratiques.utilitr.org> :
  * to be completed
  


---

# Organisation

* Des parrains
* Un groupe de contributeurs

Le projet `utilitR` est un projet collaboratif, horizontal, open source et ouvert à tous, auquel tous les agents peuvent contribuer. 
Cinq principes  : transparence, ouverture, bienveillance, exigence et reproductibilité ;
Le groupe de travail comprend environ 15 contributeurs. Tout le monde est bienvenu ;
La coordination est assurée par Lino Galiana et Olivier Meslin.


---

# Une méthode de travail pour assurer la qualité de la documentation

Le projet `utilitR` est entièrement développé avec des outils collaboratifs :

- Le projet est stocké sur un dépôt Github, sous licence libre ([https://github.com/InseeFrLab/utilitR]) ;
- La documentation est rédigée de fiches `R markdown`, publiée sous deux formes :
    - un site internet ([www.utilitr.org]) ;
    - une brochure pdf ;
- Les contributions prennent la forme de merge requests soumises à une relecture par les pairs et validées collégialement ;


- La documentation est conçue pour être intégralement reproductible :
- Le déploiement est assuré par un dispositif d’intégration continue ;
- La grande majorité des exemples utilise des données de l'Insee (code officiel géographique, répertoire Filosofi, base permanente des équipements) ;
- Nous développons en parallèle un _package_ qui contient notamment les données utilisées dans les exemples (`doremifasolData`).



