name: Slides des matinées

on:
  push:
    tags:
      - 'v*.*.gitissp'
    branches:
      - gitissp


jobs:
  xaringan-presentations:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages(c('remotes'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render
        run: |
          mkdir -p public
          Rscript -e 'rmarkdown::render("Slides_30min.Rmd")'
          Rscript -e "file.copy(here::here('resources'), here::here('public'), recursive = TRUE)"
          Rscript -e "file.copy(here::here('css'), here::here('public'), recursive = TRUE)"
          mv Slides_30min.html public/index.html
      - uses: actions/upload-artifact@v2
        with:
          name: Slides
          path: public/
          retention-days: 3
      - name: Install npm
        if: ${{ github.repository == 'inseefrlab/utilitr-presentation' }}
        uses: actions/setup-node@v1
      - name: Deploy to Netlify
        if: ${{ github.repository == 'inseefrlab/utilitr-presentation' }}
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install --unsafe-perm=true netlify-cli -g
          netlify init
          netlify deploy --alias=gitissp --dir="public" --message "Deploy gitissp"


