name: Example output

on:
  push:
    branches:
      - master

jobs:
  bookdown-prod:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: inseefrlab/utilitr:latest
    steps:
      - name: Checkout Repository
        env:
          GITHUB_PAT: ${{ secrets.PAT }}
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          Rscript -e "install.packages('xfun')"
          Rscript -e "install.packages(c('xaringan'))"
      - name: Render
        run: |
          mkdir -p public
          Rscript -e 'rmarkdown::render("slides.Rmd", output_file = "public/index.html")'
      - uses: actions/upload-artifact@v2
        with:
          name: Slides
          path: public/index.html
          retention-days: 3
      - name: Install npm
        if: ${{ github.repository == 'inseefrlab/utilitr-prez' }}
        uses: actions/setup-node@v1
      - name: Deploy to Netlify
        if: ${{ github.repository == 'inseefrlab/utilitr-prez' }}
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install --unsafe-perm=true netlify-cli -g
          netlify init
          netlify deploy --prod --dir="public" --message "Deploy master"


